### GENERAL SETTINGS ###

# Site settings
title: Bunkey Games
description: "The homepage of Michgan-based indie game-devs, Bunkey Games."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://bunkeygames.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#67E667" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#38523D" #"#33004D"
  link: "#50CA42"
  link_hover: "#44FE01"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: youtube
    url: youtube.com/BunkeyGames
  - title: twitter
    url: twitter.com/BunkeyGames

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
    - United States.
email: main@BunkeyGames.com
tel: +1 734-486-1602


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Collin B.
    position: Lead Scientist
    text: Collin does everything. That's pretty much it for him.
    img: me.jpg
    social:
      - title: envelope #use for email address
        url: mailto:collin@bunkeygames.com
      - title: twitter
        url: http://twitter.com/chuzzylumpkin

  - name: Jayce V.
    position: Lead Philosopher
    text: He's an idea and concept guy. We like to make him feel good by calling it "design".
    img: jayce.png
    social:
      - title: envelope #use for email address
        url: mailto:jayce@bunkeygames.com
      - title: youtube
        url: https://www.youtube.com/user/echoproductions098

  - name: Ace.
    position: Mystery Snack Guy
    text: Nobody really knows what's up with ACE...
    img: ace.jpg
    social:
      
    
# Clients information. Shown on Home and About pages.

  
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Bunkey Games - Giving up on projects since 2014."

# Testimonial content. Shown on Home and About page. 
